config/routes.rb
Rails.application.routes.draw do
  resources :jobs

  root 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:job_title, :company, :job_found_at, :date_applied, :employer_response_date, :salary_bool, :salary_if_known, :hourly_wage_bool, :hourly_wage_amount, :salary_amount, :interview_one, :interview_two, :interview_three, :job_notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_title %><br>
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :job_found_at %><br>
    <%= f.text_field :job_found_at %>
  </div>
  <div class="field">
    <%= f.label :date_applied %><br>
    <%= f.date_select :date_applied %>
  </div>
  <div class="field">
    <%= f.label :employer_response_date %><br>
    <%= f.date_select :employer_response_date %>
  </div>
  <div class="field">
    <%= f.label :salary_bool %><br>
    <%= f.check_box :salary_bool %>
  </div>
  <div class="field">
    <%= f.label :salary_if_known %><br>
    <%= f.check_box :salary_if_known %>
  </div>
  <div class="field">
    <%= f.label :hourly_wage_bool %><br>
    <%= f.check_box :hourly_wage_bool %>
  </div>
  <div class="field">
    <%= f.label :hourly_wage_amount %><br>
    <%= f.text_field :hourly_wage_amount %>
  </div>
  <div class="field">
    <%= f.label :salary_amount %><br>
    <%= f.number_field :salary_amount %>
  </div>
  <div class="field">
    <%= f.label :interview_one %><br>
    <%= f.text_field :interview_one %>
  </div>
  <div class="field">
    <%= f.label :interview_two %><br>
    <%= f.text_field :interview_two %>
  </div>
  <div class="field">
    <%= f.label :interview_three %><br>
    <%= f.text_field :interview_three %>
  </div>
  <div class="field">
    <%= f.label :job_notes %><br>
    <%= f.text_area :job_notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<center>
<h1>Current Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Jobs List</th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td>Job Title</td>
        <td><%= job.job_title %></td>
      </tr>
     
      <tr>
        <td>Company</td>
        <td><%= job.company %></td>
      </tr>

      <tr>
        <td>Location Found</td>
        <td><%= job.job_found_at %></td>
      </tr>

      <tr>
        <td>Date Applied</td>
        <td><%= job.date_applied %></td>
      </tr>

      <tr>
        <td>Employer Response Date</td>
        <td><%= job.employer_response_date %></td>
      </tr>

      <tr>
        <td>Job is Salary?</td>      
        <td><%= job.salary_bool %></td>
      </tr>

      <tr>
        <td>Salary</td>
        <td><%= job.salary_if_known %></td>
      </tr>

      <tr>
        <td>Hourly Wage Job?</td>
        <td><%= job.hourly_wage_bool %></td>
      </tr>

      <tr>
        <td>Hourly Wage</td>
        <td><%= job.hourly_wage_amount %></td>
      </tr>

      <tr>
        <td>Salary Amount</td>
        <td><%= job.salary_amount %></td>
      </tr> 

      <tr>
        <td>First Interview?</td>
        <td><%= job.interview_one %></td>
      </tr>

      <tr>
        <td>Second Interview?</td>
        <td><%= job.interview_two %></td>
      </tr>

      <tr>
        <td>Third Interview?</td>
        <td><%= job.interview_three %></td>
      </tr> 

      <tr>
        <td>Notes</td>
        <td><%= job.job_notes %></td>
     </tr>

      <tr>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Job', new_job_path %>
</center>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job title:</strong>
  <%= @job.job_title %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Job found at:</strong>
  <%= @job.job_found_at %>
</p>

<p>
  <strong>Date applied:</strong>
  <%= @job.date_applied %>
</p>

<p>
  <strong>Employer response date:</strong>
  <%= @job.employer_response_date %>
</p>

<p>
  <strong>Salary bool:</strong>
  <%= @job.salary_bool %>
</p>

<p>
  <strong>Salary if known:</strong>
  <%= @job.salary_if_known %>
</p>

<p>
  <strong>Hourly wage bool:</strong>
  <%= @job.hourly_wage_bool %>
</p>

<p>
  <strong>Hourly wage amount:</strong>
  <%= @job.hourly_wage_amount %>
</p>

<p>
  <strong>Salary amount:</strong>
  <%= @job.salary_amount %>
</p>

<p>
  <strong>Interview one:</strong>
  <%= @job.interview_one %>
</p>

<p>
  <strong>Interview two:</strong>
  <%= @job.interview_two %>
</p>

<p>
  <strong>Interview three:</strong>
  <%= @job.interview_three %>
</p>

<p>
  <strong>Job notes:</strong>
  <%= @job.job_notes %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobApplicationTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>